sonar.projectKey=cirujano-front
sonar.organization=cirujano-org
sonar.sources=src,backend/app
sonar.exclusions=**/node_modules/**,**/dist/**,**/tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
