export const AnalyticsEvents = {
  PAGE_VIEW: 'page_view',
  DASHBOARD_VIEW: 'dashboard_view',
  ADMIN_DASHBOARD_VIEW: 'admin_dashboard_view',
  OT_DETAIL_VIEW: 'ot_detail_view',
  SEARCH_USED: 'search_used',
  HERO_CTA_APPOINTMENT: 'hero_cta_appointment_click',
  HERO_CTA_QUOTE: 'hero_cta_quote_click',
  HERO_CTA_LOGIN: 'hero_cta_login_click',
  SECTION_FOCUS: 'section_focus',
  SCROLL_DEPTH_25: 'scroll_depth_25',
  SCROLL_DEPTH_50: 'scroll_depth_50',
  SCROLL_DEPTH_75: 'scroll_depth_75',
  SCROLL_DEPTH_100: 'scroll_depth_100',
  CONTACT_SUBMIT_SUCCESS: 'contact_submit_success',
  CONTACT_SUBMIT_ERROR: 'contact_submit_error',
  CONTACT_VALIDATION_ERROR: 'contact_validation_error',
  NEWSLETTER_SUBMIT_SUCCESS: 'newsletter_submit_success',
  NEWSLETTER_SUBMIT_ERROR: 'newsletter_submit_error',
  APPOINTMENT_SUBMIT_SUCCESS: 'appointment_submit_success',
  APPOINTMENT_SUBMIT_ERROR: 'appointment_submit_error'
}
